public class PrimitiveDatetypeDemo {
    public void print1(){
            // we will create date type 
            // String batchName = 'Batch15';
            // Integer totalCandidates = 54;
            // Boolean isAdminCompleted=true;

            // String batchDescription=batchName+' has '+totalCandidates+'';
            // System.debug(batchDescription);
            // Decimal d1 = 788.4564;
            // System.debug(d1);

            // Long l1 = 5453553454l;
            // System.debug(l1);

           
            // id accID = '01Dp000004FY3FIAW';
            // System.debug(accID);
            // all datatypes are INHERITED from obj
            Object obj1 = 233;
            Object obj2 = '233';
            Object obj3 = true;
            Object obj4 = '233';
            // Object obj5 = accID;
            System.debug(obj1);
            System.debug(obj2);
            System.debug(obj3);
            System.debug(obj4);
            // System.debug(obj5);
    }
}
