global  class SampleGlobalClass {
    global String name;
    public String description;
    private String privateDetails;

    // manage packaged mean it cannot be changed. No one see code. (.exe). App Exchange app.
    // unmanage package. One can see code. (classes and files and other components are visible).Beta testing.
    
    // Create unnamed package first
    // Create managed package from it,
}